/**
 * The Printful blanks, and the variant id behind every colour and size.
 *
 * Generated from Printful's public v1 catalogue, which needs no credentials,
 * so this file can be regenerated by anyone without a token. Variant ids are
 * stable once assigned, which is why they are committed rather than looked up
 * on every order: an order that has already been paid for must not fail
 * because a catalogue request timed out.
 *
 * Colour is chosen per garment, not per design. The blanks genuinely do not
 * share a palette: the hoodie has no Ivory or Black, and the youth tee has no
 * Pepper, so a design that runs across all three cannot be one colour.
 */

export interface Garment {
  key: string
  /** Printful catalogue product id. */
  productId: number
  /** What it actually is, for the desk and the receipt. */
  blank: string
  description: string
  /** Colour, then size, then the Printful variant id that gets ordered. */
  colors: Record<string, Record<string, number>>
}

export const GARMENTS: Record<string, Garment> = {
  ccTee: {
    key: "ccTee",
    productId: 586,
    blank: "Comfort Colors 1717",
    description: "Unisex heavyweight tee, garment dyed",
    colors: {
      "Pepper": { "2XL": 17697, "3XL": 17698, "4XL": 17699, "L": 17695, "M": 17694, "S": 17693, "XL": 17696 },
      "Ivory": { "2XL": 16527, "3XL": 16528, "4XL": 17507, "L": 16525, "M": 16524, "S": 16523, "XL": 16526 },
      "Espresso": { "2XL": 21247, "3XL": 21248, "4XL": 21249, "L": 21245, "M": 21244, "S": 21243, "XL": 21246 },
      "Blue Spruce": { "2XL": 17690, "3XL": 17691, "4XL": 17692, "L": 17688, "M": 17687, "S": 17686, "XL": 17689 },
      "Yam": { "2XL": 21275, "3XL": 21276, "4XL": 21277, "L": 21273, "M": 21272, "S": 21271, "XL": 21274 },
    },
  },
  triblendTee: {
    key: "triblendTee",
    productId: 162,
    blank: "Bella + Canvas 3413",
    description: "Unisex tri-blend tee",
    colors: {
      "Charcoal-Black Triblend": { "2XL": 6509, "3XL": 6510, "4XL": 6511, "L": 6507, "M": 6506, "S": 6505, "XL": 6508, "XS": 6504 },
      "Brown Triblend": { "2XL": 6501, "3XL": 6502, "L": 6499, "M": 6498, "S": 6497, "XL": 6500, "XS": 6496 },
      "Clay Triblend": { "2XL": 6517, "3XL": 6518, "L": 6515, "M": 6514, "S": 6513, "XL": 6516, "XS": 6512 },
      "Grey Triblend": { "2XL": 6541, "3XL": 6542, "4XL": 6543, "L": 6539, "M": 6538, "S": 6537, "XL": 6540, "XS": 6536 },
    },
  },
  ccHoodie: {
    key: "ccHoodie",
    productId: 970,
    blank: "Comfort Colors 1567",
    description: "Unisex hooded sweatshirt, garment dyed",
    colors: {
      "Pepper": { "2XL": 24854, "3XL": 24855, "L": 24852, "M": 24851, "S": 24850, "XL": 24853 },
      "Blue Spruce": { "2XL": 24818, "3XL": 24819, "L": 24816, "M": 24815, "S": 24814, "XL": 24817 },
    },
  },
  ccWomens: {
    key: "ccWomens",
    productId: 862,
    blank: "Comfort Colors 3023CL",
    description: "Women's relaxed tee, garment dyed",
    colors: {
      "Pepper": { "2XL": 22607, "L": 22597, "M": 22592, "S": 22587, "XL": 22602 },
      "Ivory": { "2XL": 22605, "L": 22595, "M": 22590, "S": 22585, "XL": 22600 },
      "Black": { "2XL": 22604, "L": 22594, "M": 22589, "S": 22584, "XL": 22599 },
    },
  },
  ccYouth: {
    key: "ccYouth",
    productId: 1411,
    blank: "Comfort Colors 1467Y",
    description: "Youth tee, garment dyed",
    colors: {
      "Ivory": { "L": 44198, "M": 44191, "S": 44184, "XL": 44205, "XS": 44177 },
      "Black": { "L": 44193, "M": 44186, "S": 44179, "XL": 44200, "XS": 44172 },
    },
  },
  triblendTank: {
    key: "triblendTank",
    productId: 163,
    blank: "Next Level 6733",
    description: "Women's racerback tank, tri-blend",
    colors: {
      "Vintage Black": { "L": 6654, "M": 6653, "S": 6652, "XL": 6655, "XS": 6651 },
      "Heather White": { "L": 6624, "M": 6623, "S": 6622, "XL": 6625, "XS": 6621 },
    },
  },
  dadHat: {
    key: "dadHat",
    productId: 206,
    blank: "Yupoong 6245CM",
    description: "Unstructured dad hat, embroidered",
    colors: {
      "Black": { "One size": 7854 },
      "Khaki": { "One size": 7855 },
      "Stone": { "One size": 7859 },
    },
  },
}

/** The variant Printful ships, or null when that colour or size is not made. */
export function variantId(garment: string, color: string, size: string): number | null {
  return GARMENTS[garment]?.colors?.[color]?.[size] ?? null
}
